### ISSUE TITLE
Add Jest example

### ISSUE THREAD

**Issue by abdonrd** [pikapkg/examples#3]
Right now, when I add Jest to the TypeScript example, the `pika build` breaks.

```
node_modules/@types/babel__core/index.d.ts(13,20): error TS2307: Cannot find module '@babel/types'.
node_modules/@types/babel__core/index.d.ts(14,31): error TS2307: Cannot find module '@babel/parser'.
node_modules/@types/babel__generator/index.d.ts(9,20): error TS2307: Cannot find module '@babel/types'.
node_modules/@types/babel__template/index.d.ts(9,31): error TS2307: Cannot find module '@babel/parser'.
node_modules/@types/babel__template/index.d.ts(10,54): error TS2307: Cannot find module '@babel/types'.
node_modules/@types/babel__traverse/index.d.ts(10,20): error TS2307: Cannot find module '@babel/types'.
node_modules/@types/babel__traverse/index.d.ts(18,5): error TS2411: Property 'scope' of type 'Scope | undefined' is not assignable to string index type 'VisitNodeObject<S, any> | VisitNodeFunction<S, any> | undefined'.
node_modules/@types/babel__traverse/index.d.ts(19,5): error TS2411: Property 'noScope' of type 'boolean | undefined' is not assignable to string index type 'VisitNodeObject<S, any> | VisitNodeFunction<S, any> | undefined'.
```

**Comment by abdonrd** [comment]
@FredKSchott you know why only with installing the `jest` package, the `pika build` command stops working?

**Comment by gr2m** [comment]
It's not a problem with `pika`, I’ve seen the same by running `tsc` directly. I’ve lost endless hours on this. Eventually `tsconfig.json` setting fixed it, but I cannot recall which one it was

**Comment by gr2m** [comment]
Try `"module": "commonjs",` for your `tsconfig.json`

```json
{
  "compilerOptions": {
    "target": "es2018",
    "module": "commonjs",
    "strict": true
  },
  "include": ["src/index.ts"],
  "exclude": ["node_modules", "**/__tests__/*"]
}
```

The builds will still be correct, but it resolves the error with jest in the "Running @pika/plugin-build-types..." step. ¯\\_(ツ)\_/¯

**Comment by gr2m** [comment]
What seems to work to is this configuration

```json
{
  "include": ["src/index.ts"]
}
```

**Comment by gr2m** [comment]
or try 

```json
{
  "compilerOptions": {
    "target": "es2018",
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true
  },
  "include": ["src/index.ts"]
}
```

![](https://media.giphy.com/media/xDQ3Oql1BN54c/giphy.gif)

**Comment by abdonrd** [comment]
It seems that it works with just the:

```
"moduleResolution": "node",
```

But with a pika warning:

```
dist-src/index.js
  ⚠️  [9:0] "./helper": Valid relative imports must include the ".js" file extension.

1 standard-pkg errors found.
```

**Comment by FredKSchott** [comment]
Ughhhhh I've run into this before with CRA. Jest does it's own compilation of your source, so having that play nicely with your build compiler can be a nightmare if they're both doing their own thing.

Let me know if you have any suggestions for what pika could do to help this. At the very least this thread seems informative

**Comment by ryaninvents** [comment]
I haven't tried anything with TypeScript yet, but from a vanilla `create-react-app` copy I found that this works in `.babelrc`:

```
{
  "presets": [
    [
      "react-app",
      {
        "useESModules": false
      }
    ]
  ],
  "env": {
    "development": {
      "presets": [
        [
          "react-app/dev",
          {
            "useESModules": true
          }
        ]
      ]
    },
    "test": {
      "presets": [
        [
          "react-app/dev",
          {
            "useESModules": true
          }
        ]
      ]
    }
  }
}

```

**Comment by Weetbix** [comment]
Should we add a separate jest example or would it be good enough to add jest and a `test`  command to the existing `simple-package` and `typescript-package` examples?
